"""init models

Revision ID: 299f134bc18e
Revises: 
Create Date: 2020-04-21 21:09:02.455388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299f134bc18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('response_text', sa.UnicodeText(), nullable=True),
    sa.Column('keywords1', sa.Unicode(), nullable=True),
    sa.Column('keywords2', sa.Unicode(), nullable=True),
    sa.Column('keywords3', sa.Unicode(), nullable=True),
    sa.Column('keywords4', sa.Unicode(), nullable=True),
    sa.Column('keywords5', sa.Unicode(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_name'), 'command', ['name'], unique=False)
    op.create_table('messenger_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=30), nullable=True),
    sa.Column('last_name', sa.Unicode(length=30), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_nkeywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], name='fk_command_nkeywords_command_id_command_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msg_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.String(length=100), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('messenger_type_id', sa.Integer(), nullable=False),
    sa.Column('dialog_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_user_id'], ['user.id'], name='fk_messenger_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext_id', 'messenger_type_id', name='_ext_id_messenger_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('use_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], name='fk_parent_id_task_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_user_id'], ['user.id'], name='fk_messenger_user_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_user_id', sa.Integer(), nullable=False),
    sa.Column('dialog_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_user_id'], ['msg_user.id'], name='fk_user_messenger_msg_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog')
    op.drop_table('task')
    op.drop_table('msg_user')
    op.drop_table('command_nkeywords')
    op.drop_table('user')
    op.drop_table('messenger_type')
    op.drop_index(op.f('ix_command_name'), table_name='command')
    op.drop_table('command')
    # ### end Alembic commands ###
