"""fix task fk

Revision ID: adb69e28469f
Revises: 299f134bc18e
Create Date: 2020-04-22 17:40:21.578189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adb69e28469f'
down_revision = '299f134bc18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog')
    op.add_column('task', sa.Column('request_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_messenger_user_user_id', 'task', type_='foreignkey')
    op.create_foreign_key('fk_msg_user_id_msg_user_id', 'task', 'msg_user', ['request_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('task', 'request_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('request_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_msg_user_id_msg_user_id', 'task', type_='foreignkey')
    op.create_foreign_key('fk_messenger_user_user_id', 'task', 'user', ['request_user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('task', 'request_user_id')
    op.create_table('dialog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dialog_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_user_id'], ['msg_user.id'], name='fk_user_messenger_msg_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dialog_pkey')
    )
    # ### end Alembic commands ###
